create table tb_produto (id int8 generated by default as identity, nm_nome varchar(255), valor numeric(19, 2), primary key (id));
create table tb_produto (id int8 generated by default as identity, nm_nome varchar(255), valor numeric(19, 2), primary key (id));
create table tb_produto (id int8 generated by default as identity, nm_nome varchar(255), valor numeric(19, 2), primary key (id));
